### ISSUE TITLE
 Error al colocar servidor de mail inválido al Recuperar Contraseña

### ISSUE THREAD

**Issue by matiasdemarchi** [PyAr/OpenLex#46]
Ocurre un error al intentar recuperar la contraseña usando un servidor de mail que no existe o es inválido. Propongo la elaboración de una salida de excepción para eventuales casos de errores de tipeo. El error fue así:

Error ticket for "OpenLex"

<class 'Exception'> Server address not specified

Versión
web2py™ | Version 2.21.1-stable+timestamp.2020.11.27.18.21.43
Python 3.7.3: /usr/bin/python3 (prefix: /usr)

Rastreo

1. Traceback (most recent call last):
2.   File "/home/myuser/web2py/gluon/restricted.py", line 219, in restricted
3.     exec(ccode, environment)
4.   File "/home/myuser/web2py/applications/OpenLex/controllers/default.py", line 57, in <module>
5.   File "/home/myuser/web2py/gluon/globals.py", line 430, in <lambda>
6.     self._caller = lambda f: f()
7.   File "/home/myuser/web2py/applications/OpenLex/controllers/default.py", line 55, in user
8.     return dict(form=auth())
9.   File "/home/myuser/web2py/gluon/tools.py", line 1809, in __call__
10.     return getattr(self, args[0])()
11.   File "/home/myuser/web2py/gluon/tools.py", line 3503, in request_reset_password
12.     if self.email_reset_password(user):
13.   File "/home/myuser/web2py/gluon/tools.py", line 3527, in email_reset_password
14.     message=self.messages.reset_password % d):
15.   File "/home/myuser/web2py/gluon/tools.py", line 431, in send
16.     raise Exception('Server address not specified')
17. Exception: Server address not specified

Frames

    File /home/myuser/web2py/gluon/restricted.py in restricted at line 219

    File /home/myuser/web2py/applications/OpenLex/controllers/default.py in <module> at line 57

    File /home/myuser/web2py/gluon/globals.py in <lambda> at line 430

    File /home/myuser/web2py/applications/OpenLex/controllers/default.py in user at line 55

    File /home/myuser/web2py/gluon/tools.py in __call__ at line 1809

    File /home/myuser/web2py/gluon/tools.py in request_reset_password at line 3503

    File /home/myuser/web2py/gluon/tools.py in email_reset_password at line 3527

    File /home/myuser/web2py/gluon/tools.py in send at line 431

**Function argument list**

(self=<gluon.tools.Mail object>, to='example@example.com', subject=<lazyT 'Password reset'>, message=<lazyT 'Click on the link %(link)s to reset your password'>, attachments=None, cc=None, bcc=None, reply_to=None, sender=None, encoding='utf-8', raw=False, headers={}, from_address=None, cipher_type=None, sign=None, sign_passphrase=None, encrypt=None, x509_sign_keyfile=None, x509_sign_chainfile=None, x509_sign_certfile=None, x509_crypt_certfiles=None, x509_nocerts=None)

**Code listing**

426.            return text
427.
428.        sender = sender or self.settings.sender
429.
430.        if not isinstance(self.settings.server, str):
431.            raise Exception('Server address not specified')
432.        if not isinstance(sender, str):
433.            raise Exception('Sender address not specified')
434.
435.        if not raw and attachments:

**Variables**
builtinException <class 'Exception'>

In file: /home/myuser/web2py/applications/OpenLex/controllers/default.py 
1. <code object <module> at 0x7f65a854e8a0, file "/home/myuser/web2py/applications/OpenLex/controllers/default.py", line 2>

[Link del issue](https://github.com/matiasdemarchi/OpenLex/issues/5#issue-931085486)

**Comment by Juerodriguez** [comment]
- Verificacion de correo.

https://github.com/haimavni/place_stories_server/blob/a510aa0fcb659b13a9860cbe5d091f862f1006fa/modules/my_auth.py

**Comment by Juerodriguez** [comment]
Estuve viendo otra solucion que es restringir el login al usuario la segunda vez que entre si no verifica su correo electronico.
La solucion aparece en Web2py book.
![restricciones](https://user-images.githubusercontent.com/73370773/126656265-2bec4670-db36-4657-8967-2d7bbabe2171.png)

@eamanu, @matiasdemarchi , @marian-vignau.
