### ISSUE TITLE
Error al ingresar a la pestaña "Expedientes"

### ISSUE THREAD

**Issue by goncho123** [PyAr/OpenLex#68]
<h2>Error ticket for "OpenLex"</h2>
<h3>Ticket ID</h3>
<p>127.0.0.1.2022-05-10.17-18-21.99a2f4ca-6e3d-40c4-9c93-9dbeada7faf4</p>
<h4>&lt;class 'ModuleNotFoundError'&gt; No module named 'applications.OpenLex.modules.xhtml2pdf'</h4>
<h3>Versión</h3>

web2py™ | Version 2.22.3-stable+timestamp.2022.02.15.07.07.56
-- | --
Python 3.8.10: /usr/bin/python3 (prefix: /usr)

</div>

<h3>Error snapshot
  <a href="http://127.0.0.1:8000/admin/default/ticket/OpenLex/127.0.0.1.2022-05-10.17-18-21.99a2f4ca-6e3d-40c4-9c93-9dbeada7faf4#" rel="tooltip" data-placement="right" data-original-title="Descripción detallada del rastreo">
    <img alt="help" src="http://127.0.0.1:8000/admin/static/_2.22.3/images/help.png">
    
  </a>
</h3>

<div id="snapshot">
  
  <p class="exception_object inspect">
    <code>ModuleNotFoundError(No module named 'applications.OpenLex.modules.xhtml2pdf')</code>
  </p></div>Error ticket for "OpenLex"
Ticket ID

127.0.0.1.2022-05-10.17-18-21.99a2f4ca-6e3d-40c4-9c93-9dbeada7faf4
<class 'ModuleNotFoundError'> No module named 'applications.OpenLex.modules.xhtml2pdf'
Versión
web2py™ 	Version 2.22.3-stable+timestamp.2022.02.15.07.07.56
Python 	Python 3.8.10: /usr/bin/python3 (prefix: /usr)
Rastreo

1.
2.
3.
4.
5.
6.
7.
8.
9.

	

Traceback (most recent call last):
  File "/home/gonzalo/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File ["/home/gonzalo/web2py/applications/OpenLex/controllers/expedientes.py"](http://127.0.0.1:8000/admin/default/edit/OpenLex/controllers/expedientes.py), line 9, in <module>
    from xhtml2pdf import pisa
  File "/home/gonzalo/web2py/gluon/custom_import.py", line 85, in custom_importer
    return base_importer(pname, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'applications.OpenLex.modules.xhtml2pdf'

Error snapshot help

ModuleNotFoundError(No module named 'applications.OpenLex.modules.xhtml2pdf')

**Comment by ljguzman** [comment]
Este problema se resuelve instalando xhtml2pdf versión 0.2.6 o superior.

En el archivo requirements.txt figura xhtml2pdf==0.2.5 pero con esta versión también muestra ese error.
